### ISSUE TITLE
Can't compile on linux

### ISSUE THREAD

**Issue by Cdrei** [RoccoLoxPrograms/Adventure#1]
I receive the following error, when attempting to compile on Linux:

make: cedev-config: No such file or directory
make: *** No rule to make target '/font/AdventureFont.fnt', needed by '/font/AdventureFont.inc'.  Stop.

**Comment by TIny-Hacker** [comment]
You need to install the CE C toolchain and add it to your PATH. You can follow the directions to do that here: https://ce-programming.github.io/toolchain/static/getting-started.html
